# Generated by Django 5.1.1 on 2024-09-22 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_price', models.IntegerField(default=200000)),
                ('down_payment', models.IntegerField(default=30000)),
                ('closing_costs', models.FloatField(default=3.5)),
                ('loan_term', models.IntegerField(default=30)),
                ('interest_rate', models.FloatField(default=5.95)),
                ('property_tax', models.FloatField(default=1.1)),
                ('insurance_rate', models.FloatField(default=0.5)),
                ('hoa', models.IntegerField(default=0)),
                ('gas', models.IntegerField(default=20)),
                ('electricity', models.IntegerField(default=200)),
                ('internet', models.IntegerField(default=120)),
                ('water_trash', models.IntegerField(default=90)),
                ('person1_contribution', models.IntegerField(default=1875)),
                ('person2_contribution', models.IntegerField(default=1875)),
                ('savings_goal', models.IntegerField(default=50000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
