# Generated by Django 5.1.1 on 2024-11-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortgagecalculation',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='mortgagecalculation',
            name='person1_contribution',
        ),
        migrations.RemoveField(
            model_name='mortgagecalculation',
            name='person2_contribution',
        ),
        migrations.RemoveField(
            model_name='mortgagecalculation',
            name='savings_goal',
        ),
        migrations.AddField(
            model_name='mortgagecalculation',
            name='name',
            field=models.CharField(default='New Home', max_length=100),
        ),
    ]
